import { StyleSheet, Platform } from 'react-native';
import { PURPLE } from '../../../../../core/presentation/designsystem/components/CommonStyles';
 
export const gestionUsuariosStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: 'white',
  },
 
  // Header morado — mismo patrón que MisPatronesScreen
  header: {
    backgroundColor: PURPLE,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 14,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
  },
 
// Barra de búsqueda dentro del header morado
  searchHeader: {
    backgroundColor: PURPLE,
    paddingHorizontal: 20,
    paddingBottom: 14,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 10,
    paddingHorizontal: 12,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    height: 40,
    paddingVertical: Platform.OS === 'ios' ? 10 : 6,
    fontSize: 14,
    color: '#333',
  },
  filtrosContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    alignItems: 'center',
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  filtroGrid: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#F3EDF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filtroGridActivo: {
    backgroundColor: PURPLE,
  },
  filtroPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F0F0F0',
  },
  filtroPillActivo: {
    backgroundColor: PURPLE,
  },
  filtroPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#555',
  },
  filtroPillTextActivo: {
    color: 'white',
  },
 
  // Contador de resultados 
  resultsCount: {
    fontSize: 13,
    color: '#555',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  actionErrorText: {
    color: '#C0392B',
    fontSize: 13,
    fontWeight: '600',
    paddingHorizontal: 16,
    paddingBottom: 6,
  },
 
  // Lista
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 80,
    gap: 12,
  },
  addUserFab: {
    position: 'absolute',
    right: 18,
    bottom: 86,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 12,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
 
  // Card de cada usuario
  userCard: {
    backgroundColor: 'white',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    height: 116,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },

  avatarImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
    marginRight: 12,
    borderWidth: 2,
    borderColor: PURPLE,
  },
  avatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#E4E4E4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  userInfo: {
    flex: 1,
  },
  userTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  userName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  moreButton: {
    padding: 4,
  },
  userEmailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  userEmail: {
    fontSize: 12.5,
    color: '#777',
  },
  userId: {
    fontSize: 12,
    color: '#999',
  },
  userMetaRow: {
    flexDirection: 'row',
    marginTop: 6,
  },
  userMetaText: {
    fontSize: 12.5,
    color: '#555',
  },
  userMetaSeparator: {
    fontSize: 12.5,
    color: '#CCC',
    marginHorizontal: 6,
  },
  userDateText: {
    fontSize: 12,
    color: '#888',
    marginTop: 4,
  },
  rolAdminText: {
    color: PURPLE,
    fontWeight: '700',
  },
  estadoActivoText: {
    color: '#1F9254',
    fontWeight: '600',
  },
  estadoSuspendidoText: {
    color: '#C0392B',
    fontWeight: '600',
  },
 
  // ── Overlay de acciones (editar / estado / eliminar) ──────────────────────
  // Reemplaza visualmente la card seleccionada — mismo tamaño y posición,
  // con 3 botones circulares centrados y una X para cerrar.
  actionsOverlay: {
    backgroundColor: PURPLE,
    borderRadius: 14,
    height: 116,
    paddingVertical: 18,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    position: 'relative',
  },
  closeOverlayButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E53935',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    zIndex: 5,
  },
  overlayAction: {
    alignItems: 'center',
    gap: 6,
    width: 88,
  },
  overlayIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayActionLabel: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
 
  // ── Estados: cargando / vacío / error / acceso denegado ───────────────────
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  centerStateText: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 12,
  },
  retryButton: {
    marginTop: 16,
    backgroundColor: PURPLE,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 10,
  },
  retryButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 14,
  },
  deniedTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 6,
    marginTop: 12,
  },
  deniedText: {
    fontSize: 14,
    color: '#888',
    textAlign: 'center',
  },
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 34,
  },
  deleteModalCard: {
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 18,
    padding: 26,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  deleteModalIcon: {
    width: 62,
    height: 62,
    borderRadius: 31,
    borderWidth: 2,
    borderColor: PURPLE,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  deleteModalTitle: {
    color: '#1A1A1A',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  deleteModalActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
  },
  deleteCancelButton: {
    flex: 1,
    backgroundColor: PURPLE,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  deleteCancelButtonText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '700',
  },
  deleteConfirmButton: {
    flex: 1,
    backgroundColor: 'white',
    borderWidth: 1.5,
    borderColor: PURPLE,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  deleteConfirmButtonText: {
    color: PURPLE,
    fontSize: 15,
    fontWeight: '700',
  },
  suspensionFields: {
    width: '100%',
    gap: 12,
    marginBottom: 22,
  },
  suspensionLabel: {
    alignSelf: 'flex-start',
    color: '#111',
    fontSize: 14,
    fontWeight: '800',
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: PURPLE,
    marginBottom: 8,
  },
  suspensionInput: {
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 8,
    height: 44,
    paddingHorizontal: 12,
    color: '#333',
    fontSize: 14,
  },
  suspensionTextArea: {
    height: 84,
    paddingTop: 10,
    textAlignVertical: 'top',
  },
  suspensionHelpText: {
    color: '#666',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 22,
  },
  suspensionErrorText: {
    color: '#C0392B',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 14,
  },
  editSafeArea: {
    flex: 1,
    backgroundColor: 'white',
  },
  editContent: {
    flexGrow: 1,
    paddingHorizontal: 52,
    paddingTop: 18,
    paddingBottom: 42,
  },
  editBackButton: {
    marginLeft: -32,
  },
  editTitle: {
    color: '#262626',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 28,
  },
  editFieldGroup: {
    marginBottom: 26,
  },
  editLabel: {
    alignSelf: 'flex-start',
    color: '#111',
    fontSize: 15,
    fontWeight: '800',
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: PURPLE,
    marginBottom: 12,
  },
  editInput: {
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 7,
    height: 46,
    paddingHorizontal: 14,
    color: '#333',
    fontSize: 15,
  },
  editSelectButton: {
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 7,
    minHeight: 46,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  editSelectText: {
    color: '#333',
    fontSize: 15,
  },
  editSaveButton: {
    backgroundColor: PURPLE,
    borderRadius: 7,
    minHeight: 45,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 34,
  },
  editSaveButtonDisabled: {
    opacity: 0.65,
  },
  editSaveButtonText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '800',
  },
  passwordToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: -2,
    marginBottom: 22,
  },
  passwordToggleText: {
    color: '#111',
    fontSize: 15,
    fontWeight: '800',
  },
  animatedPasswordFields: {
    overflow: 'hidden',
  },
  passwordUpdateButton: {
    marginTop: 0,
  },
  editErrorText: {
    color: '#C0392B',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 18,
  },
  editLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addUserContent: {
    flexGrow: 1,
    paddingHorizontal: 52,
    paddingTop: 18,
    paddingBottom: 42,
  },
  addAvatarWrapper: {
    alignSelf: 'center',
    marginTop: -8,
    marginBottom: 28,
  },
  addAvatarPlaceholder: {
    width: 192,
    height: 192,
    borderRadius: 96,
    backgroundColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: PURPLE,
  },
  addAvatarImage: {
    width: 192,
    height: 192,
    borderRadius: 96,
    borderWidth: 2,
    borderColor: PURPLE,
  },
  addAvatarBadge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'white',
  },
  editAvatarWrapper: {
    alignSelf: 'center',
    marginTop: -8,
    marginBottom: 28,
  },
  editAvatarPlaceholder: {
    width: 192,
    height: 192,
    borderRadius: 96,
    backgroundColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: PURPLE,
  },
  editAvatarImage: {
    width: 192,
    height: 192,
    borderRadius: 96,
    borderWidth: 2,
    borderColor: PURPLE,
  },
  editAvatarBadge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'white',
  },
  lockedInputContainer: {
    backgroundColor: '#EFEFEF',
    borderColor: '#CFCFCF',
  },
  fieldActionIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  addPasswordInputContainer: {
    height: 46,
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 7,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addPasswordInput: {
    flex: 1,
    color: '#333',
    fontSize: 15,
    paddingVertical: 0,
  },
  statusModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'center',
    paddingHorizontal: 52,
  },
  statusModalCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  statusOption: {
    paddingHorizontal: 18,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusOptionText: {
    color: '#333',
    fontSize: 15,
    fontWeight: '600',
  },
});
