import { StyleSheet, Platform } from 'react-native';
import Colors from '../../../../core/presentation/designsystem/Colors';

export const PURPLE = Colors.primary;

export const createCrearStyles = (colors = Colors.light) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 14,
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: colors.text,
    paddingHorizontal: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
    gap: 20,
  },
  section: {
    gap: 8,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  patternList: {
    gap: 10,
    paddingHorizontal: 16,
  },
  patternScroll: {
    marginHorizontal: -16,
  },
  patternCard: {
    width: 110,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'transparent',
    backgroundColor: colors.surface,
  },
  patternCardSelected: {
    borderColor: PURPLE,
  },
  patternThumb: {
    width: 110,
    height: 90,
    backgroundColor: colors.imageBackground,
  },
  patternThumbPlaceholder: {
    width: 110,
    height: 90,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  patternCardName: {
    fontSize: 11,
    color: colors.textSecondary,
    padding: 6,
    fontWeight: '500',
  },
  patternCardNameSelected: {
    color: PURPLE,
    fontWeight: '700',
  },
  noPatterns: {
    fontSize: 14,
    color: colors.iconMuted,
    textAlign: 'center',
    paddingVertical: 20,
  },
  textArea: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: colors.text,
    height: 90,
    textAlignVertical: 'top',
    backgroundColor: colors.surface,
  },
  techniqueRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  techniquePill: {
    borderWidth: 1.5,
    borderColor: colors.modalHandle,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 7,
    backgroundColor: colors.surface,
  },
  techniquePillSelected: {
    borderColor: PURPLE,
    backgroundColor: colors.primarySoft,
  },
  techniquePillText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  techniquePillTextSelected: {
    color: colors.communityTechniqueText,
    fontWeight: '700',
  },
  otrosInput: {
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 42,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.surface,
    marginTop: 8,
  },
  imagePickerBtn: {
    borderWidth: 1.5,
    borderColor: colors.modalHandle,
    borderRadius: 12,
    borderStyle: 'dashed',
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.surface,
  },
  imagePickerText: {
    fontSize: 13,
    color: colors.textMuted,
  },
  selectedImageContainer: {
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  selectedImage: {
    width: '100%',
    height: 180,
    borderRadius: 12,
  },
  removeImageBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: colors.overlayStrong,
    borderRadius: 14,
    padding: 4,
  },
  submitBtn: {
    backgroundColor: PURPLE,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 8,
  },
  submitBtnDisabled: {
    backgroundColor: colors.disabledButtonBackground,
  },
  submitBtnText: {
    color: Colors.fixedWhite,
    fontSize: 16,
    fontWeight: '700',
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  savedPatternNote: {
    fontSize: 12,
    color: Colors.errorStrong,
    marginBottom: 8,
    marginTop: 2,
  },
  savedLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingBottom: 4,
  },
  savedLabelText: {
    fontSize: 10,
    color: PURPLE,
    fontWeight: '600',
  },
  suspensionContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    gap: 16,
  },
  suspensionIconWrapper: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: colors.dangerBackground,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  suspensionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textHeading,
    textAlign: 'center',
  },
  suspensionMessage: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 21,
  },
  suspensionDateBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primarySoft,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 4,
  },
  suspensionDateText: {
    fontSize: 14,
    color: PURPLE,
    fontWeight: '600',
  },
  suspensionDaysChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.dangerBackground,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  suspensionDaysText: {
    fontSize: 13,
    color: Colors.errorStrong,
    fontWeight: '700',
  },
});

export const crearStyles = createCrearStyles(Colors.light);
