import { StyleSheet, Platform } from 'react-native';
import Colors from '../../../../core/presentation/designsystem/Colors';

export const PURPLE = Colors.primary;

export const createDetalleStyles = (colors = Colors.light) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
    paddingBottom: 14,
  },
  headerTitle: {
    flex: 1,
    fontSize: 30,
    fontWeight: '800',
    color: colors.text,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  deleteBtn: {
    padding: 6,
  },
  saveBtn: {
    padding: 6,
  },
  scroll: {
    flex: 1,
  },
  imageBlock: {
    position: 'relative',
  },
  image: {
    width: '100%',
    height: 280,
    backgroundColor: colors.imageBackground,
  },
  imageSmall: {
    width: '100%',
    height: 200,
    backgroundColor: colors.background,
  },
  imagePlaceholder: {
    width: '100%',
    height: 200,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageLabelBadge: {
    position: 'absolute',
    bottom: 8,
    left: 10,
    backgroundColor: colors.overlayStrong,
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    zIndex: 1,
  },
  imageLabelText: {
    color: Colors.fixedWhite,
    fontSize: 11,
    fontWeight: '600',
  },
  imageDivider: {
    height: 3,
    backgroundColor: colors.borderSoft,
  },
  body: {
    padding: 16,
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 38,
    height: 38,
    borderRadius: 19,
  },
  avatarText: {
    color: Colors.fixedWhite,
    fontSize: 15,
    fontWeight: '700',
  },
  authorInfo: {
    flex: 1,
  },
  authorName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  publishedDate: {
    fontSize: 12,
    color: colors.iconMuted,
    marginTop: 1,
  },
  techniqueBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primarySoft,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 10,
  },
  techniqueBadgeText: {
    color: colors.communityTechniqueText,
    fontSize: 12,
    fontWeight: '600',
  },
  description: {
    fontSize: 15,
    color: colors.text,
    lineHeight: 22,
    marginBottom: 8,
  },
  patternName: {
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: 16,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 16,
  },
  commentsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
  },
  commentItem: {
    marginBottom: 14,
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  commentAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentAvatarImage: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  commentAvatarText: {
    color: Colors.fixedWhite,
    fontSize: 11,
    fontWeight: '700',
  },
  commentAuthor: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  commentActions: {
    flexDirection: 'row',
    gap: 8,
  },
  commentActionBtn: {
    padding: 3,
  },
  commentContent: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
    paddingLeft: 36,
  },
  commentDate: {
    fontSize: 11,
    color: colors.textDisabled,
  },
  commentDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingLeft: 36,
    marginTop: 2,
  },
  commentEditedText: {
    fontSize: 11,
    color: colors.textSubtle,
    fontWeight: '600',
  },
  noComments: {
    fontSize: 14,
    color: colors.textDisabled,
    textAlign: 'center',
    paddingVertical: 16,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    paddingBottom: Platform.OS === 'ios' ? 26 : 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 14,
    color: colors.text,
    height: 38,
    backgroundColor: colors.surface,
  },
  sendBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    backgroundColor: colors.modalHandle,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.background,
    zIndex: 20,
  },
  cancelEditBtn: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  editingBanner: {
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  editingBannerText: {
    fontSize: 12,
    color: PURPLE,
    fontWeight: '500',
  },
  fullscreenOverlay: {
    flex: 1,
    backgroundColor: Colors.fixedBlack,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenImage: {
    width: '100%',
    height: '100%',
  },
  fullscreenClose: {
    position: 'absolute',
    top: 50,
    right: 16,
    backgroundColor: colors.overlayStrong,
    borderRadius: 20,
    padding: 8,
    zIndex: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 24,
    width: '80%',
    alignItems: 'center',
    gap: 12,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
  },
  modalMessage: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  modalDanger: {
    backgroundColor: Colors.errorStrong,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: '100%',
    alignItems: 'center',
  },
  modalDangerText: {
    color: Colors.fixedWhite,
    fontWeight: '700',
    fontSize: 15,
  },
  modalCancel: {
    paddingVertical: 8,
  },
  modalCancelText: {
    color: colors.textMuted,
    fontSize: 14,
  },
  suspendedInputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
    backgroundColor: colors.dangerBackground,
  },
  suspendedInputText: {
    fontSize: 13,
    color: Colors.errorStrong,
    flex: 1,
  },
});

export const detalleStyles = createDetalleStyles(Colors.light);
