import { StyleSheet, Platform } from 'react-native';

export const PURPLE = '#763A6C';

export const detalleStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: 'white',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    backgroundColor: 'white',
  },
  backBtn: {
    padding: 6,
    marginRight: 8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
    color: '#222',
  },
  deleteBtn: {
    padding: 6,
  },
  saveBtn: {
    padding: 6,
  },
  scroll: {
    flex: 1,
  },
  imageBlock: {
    position: 'relative',
  },
  image: {
    width: '100%',
    height: 280,
    backgroundColor: '#EEE',
  },
  imageSmall: {
    width: '100%',
    height: 200,
    backgroundColor: '#F5F5F5',
  },
  imagePlaceholder: {
    width: '100%',
    height: 200,
    backgroundColor: '#F0E8EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageLabelBadge: {
    position: 'absolute',
    bottom: 8,
    left: 10,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    zIndex: 1,
  },
  imageLabelText: {
    color: 'white',
    fontSize: 11,
    fontWeight: '600',
  },
  imageDivider: {
    height: 3,
    backgroundColor: '#F0F0F0',
  },
  body: {
    padding: 16,
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 38,
    height: 38,
    borderRadius: 19,
  },
  avatarText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '700',
  },
  authorInfo: {
    flex: 1,
  },
  authorName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#222',
  },
  publishedDate: {
    fontSize: 12,
    color: '#AAA',
    marginTop: 1,
  },
  techniqueBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F0E8EF',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 10,
  },
  techniqueBadgeText: {
    color: PURPLE,
    fontSize: 12,
    fontWeight: '600',
  },
  description: {
    fontSize: 15,
    color: '#333',
    lineHeight: 22,
    marginBottom: 8,
  },
  patternName: {
    fontSize: 13,
    color: '#888',
    marginBottom: 16,
  },
  divider: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 16,
  },
  commentsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#222',
    marginBottom: 12,
  },
  commentItem: {
    marginBottom: 14,
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  commentAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentAvatarImage: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  commentAvatarText: {
    color: 'white',
    fontSize: 11,
    fontWeight: '700',
  },
  commentAuthor: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
  },
  commentActions: {
    flexDirection: 'row',
    gap: 8,
  },
  commentActionBtn: {
    padding: 3,
  },
  commentContent: {
    fontSize: 14,
    color: '#444',
    lineHeight: 20,
    paddingLeft: 36,
  },
  commentDate: {
    fontSize: 11,
    color: '#BBB',
    paddingLeft: 36,
    marginTop: 2,
  },
  noComments: {
    fontSize: 14,
    color: '#BBB',
    textAlign: 'center',
    paddingVertical: 16,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    paddingBottom: Platform.OS === 'ios' ? 26 : 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
    backgroundColor: 'white',
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 14,
    color: '#333',
    height: 38,
    backgroundColor: '#FAFAFA',
  },
  sendBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    backgroundColor: '#DDD',
  },
  cancelEditBtn: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  editingBanner: {
    backgroundColor: '#F0E8EF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  editingBannerText: {
    fontSize: 12,
    color: PURPLE,
    fontWeight: '500',
  },
  fullscreenOverlay: {
    flex: 1,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenImage: {
    width: '100%',
    height: '100%',
  },
  fullscreenClose: {
    position: 'absolute',
    top: 50,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    padding: 8,
    zIndex: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    backgroundColor: 'white',
    borderRadius: 18,
    padding: 24,
    width: '80%',
    alignItems: 'center',
    gap: 12,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#222',
  },
  modalMessage: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
  },
  modalDanger: {
    backgroundColor: '#E53935',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: '100%',
    alignItems: 'center',
  },
  modalDangerText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 15,
  },
  modalCancel: {
    paddingVertical: 8,
  },
  modalCancelText: {
    color: '#888',
    fontSize: 14,
  },
});
