import { StyleSheet } from 'react-native';
import Colors from '../../../../../core/presentation/designsystem/Colors';
import { PURPLE } from '../../../../../core/presentation/designsystem/components/CommonStyles';

export { PURPLE } from '../../../../../core/presentation/designsystem/components/CommonStyles';

export const createAdminCommunityManagementStyles = (colors = Colors.light) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: PURPLE,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
  },
  headerTitle: {
    color: Colors.fixedWhite,
    fontSize: 28,
    fontWeight: '800',
  },
  tabs: {
    height: 42,
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
    position: 'relative',
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    borderBottomColor: PURPLE,
  },
  tabIndicator: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    height: 2,
    backgroundColor: PURPLE,
  },
  tabText: {
    color: colors.textStrong,
    fontSize: 13,
    fontWeight: '700',
  },
  tabTextActive: {
    color: PURPLE,
  },
  filtrosContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    alignItems: 'center',
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    zIndex: 1
  },
  filtroGrid: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: colors.primarySubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filtroGridActivo: {
    backgroundColor: PURPLE,
  },
  filtroPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.borderSoft,
  },
  filtroPillActivo: {
    backgroundColor: PURPLE,
  },
  filtroPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  filtroPillTextActivo: {
    color: Colors.fixedWhite,
  },
  body: {
    flex: 1,
    backgroundColor: colors.inputBackground,
  },
  contentScroll: {
    flex: 1,
  },
  commentsContent: {
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 12,
    gap: 12,
  },
  emptyContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
  },
  commentCard: {
    minHeight: 98,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 7,
    elevation: 4,
  },
  commentAvatarBlock: {
    width: 86,
    alignItems: 'center',
    gap: 5,
  },
  avatarImage: {
    borderWidth: 1.5,
    borderColor: PURPLE,
    backgroundColor: colors.imageBackground,
  },
  avatarFallback: {
    borderWidth: 1.5,
    borderColor: PURPLE,
    backgroundColor: colors.modalHandle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentUserName: {
    color: colors.textStrong,
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 82,
  },
  commentBody: {
    flex: 1,
    paddingRight: 0,
  },
  commentMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  commentMeta: {
    color: colors.textSubtle,
    fontSize: 12,
  },
  commentMetaSeparator: {
    color: Colors.gray475,
    fontSize: 12,
  },
  commentPublicationLink: {
    color: PURPLE,
    fontSize: 12,
    fontWeight: '800',
  },
  commentText: {
    color: colors.textSubtle,
    fontSize: 12,
    lineHeight: 16,
  },
  cardActionMenu: {
    position: 'absolute',
    top: 9,
    right: 9,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    zIndex: 8,
  },
  cardActionMenuDown: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  cardActionMenuItems: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'flex-end',
    overflow: 'hidden',
    marginRight: 6,
  },
  cardActionMenuItemsDown: {
    gap: 6,
    alignItems: 'flex-end',
    overflow: 'hidden',
    marginTop: 6,
  },
  cardActionMenuItem: {
    width: 32,
    alignItems: 'center',
  },
  cardActionToggle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: PURPLE,
    elevation: 5,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  cardActionToggleOpen: {
    backgroundColor: colors.surface,
  },
  publicationsContent: {
    padding: 8,
    paddingBottom: 8,
  },
  publicationColumns: {
    flexDirection: 'row',
    gap: 8,
  },
  publicationColumn: {
    flex: 1,
    gap: 8,
  },
  publicationCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  publicationImage: {
    width: '100%',
    height: 160,
    backgroundColor: colors.imageBackground,
  },
  publicationImageTall: {
    height: 210,
  },
  publicationPlaceholder: {
    width: '100%',
    height: 160,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportCountText: {
    color: Colors.fixedWhite,
    fontSize: 12,
    fontWeight: '800',
  },
  publicationInfo: {
    padding: 10,
  },
  publicationDescription: {
    color: colors.text,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 6,
  },
  publicationAuthorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  publicationAuthor: {
    flex: 1,
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '500',
  },
  techniqueBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primarySoft,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginBottom: 5,
  },
  techniqueBadgeText: {
    color: colors.communityTechniqueText,
    fontSize: 10,
    fontWeight: '700',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    gap: 12,
  },
  emptyText: {
    color: colors.textSubtle,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: PURPLE,
    borderRadius: 10,
    paddingHorizontal: 22,
    paddingVertical: 11,
  },
  retryButtonText: {
    color: Colors.fixedWhite,
    fontSize: 14,
    fontWeight: '800',
  },
  disabledItem: {
    opacity: 0.55,
  },
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 34,
  },
  deleteModalCard: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 26,
    alignItems: 'center',
    elevation: 10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  deleteModalIcon: {
    width: 62,
    height: 62,
    borderRadius: 31,
    borderWidth: 2,
    borderColor: PURPLE,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  deleteModalTitle: {
    color: colors.textHeading,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  deleteModalActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
  },
  deleteCancelButton: {
    flex: 1,
    backgroundColor: PURPLE,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  deleteCancelButtonText: {
    color: Colors.fixedWhite,
    fontSize: 15,
    fontWeight: '700',
  },
  deleteConfirmButton: {
    flex: 1,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: PURPLE,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  deleteConfirmButtonText: {
    color: PURPLE,
    fontSize: 15,
    fontWeight: '700',
  },
  reportSafeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  reportContent: {
    flex: 1,
    paddingHorizontal: 52,
    paddingTop: 18,
  },
  reportBackButton: {
    marginLeft: -32,
  },
  reportTitle: {
    color: colors.textStrong,
    fontSize: 29,
    fontWeight: '800',
    lineHeight: 36,
    marginBottom: 30,
  },
  reportFieldGroup: {
    marginBottom: 27,
  },
  reportLabel: {
    alignSelf: 'flex-start',
    color: colors.textStrong,
    fontSize: 15,
    fontWeight: '800',
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: PURPLE,
    marginBottom: 12,
  },
  reportInput: {
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 7,
    height: 46,
    paddingHorizontal: 14,
    color: colors.text,
    fontSize: 15,
  },
  reportTextArea: {
    height: 134,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  reportErrorText: {
    color: Colors.errorDark,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: -6,
    marginBottom: 16,
  },
  reportPrimaryButton: {
    backgroundColor: PURPLE,
    borderRadius: 7,
    minHeight: 45,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 34,
  },
  reportPrimaryButtonText: {
    color: Colors.fixedWhite,
    fontSize: 15,
    fontWeight: '800',
  },
  reportDangerButton: {
    backgroundColor: PURPLE,
    borderRadius: 7,
    minHeight: 45,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
  },
  reportDangerButtonText: {
    color: Colors.fixedWhite,
    fontSize: 15,
    fontWeight: '800',
  },
  reportButtonDisabled: {
    opacity: 0.65,
  },
});

export const adminCommunityManagementStyles = createAdminCommunityManagementStyles(Colors.light);
