import { StyleSheet } from 'react-native';
import { PURPLE } from '../../../../../core/presentation/designsystem/components/CommonStyles';

export { PURPLE } from '../../../../../core/presentation/designsystem/components/CommonStyles';

export const adminCommunityManagementStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: 'white',
  },
  header: {
    backgroundColor: PURPLE,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
  },
  headerTitle: {
    color: 'white',
    fontSize: 28,
    fontWeight: '800',
  },
  tabs: {
    height: 42,
    flexDirection: 'row',
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#D8D8D8',
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabButtonActive: {
    borderBottomColor: PURPLE,
  },
  tabText: {
    color: '#111',
    fontSize: 13,
    fontWeight: '700',
  },
  tabTextActive: {
    color: PURPLE,
  },
  filtrosContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    alignItems: 'center',
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  filtroGrid: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#F3EDF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filtroGridActivo: {
    backgroundColor: PURPLE,
  },
  filtroPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F0F0F0',
  },
  filtroPillActivo: {
    backgroundColor: PURPLE,
  },
  filtroPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#555',
  },
  filtroPillTextActivo: {
    color: 'white',
  },
  body: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  contentScroll: {
    flex: 1,
  },
  commentsContent: {
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 96,
    gap: 12,
  },
  commentCard: {
    minHeight: 98,
    backgroundColor: 'white',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 7,
    elevation: 4,
  },
  commentAvatarBlock: {
    width: 86,
    alignItems: 'center',
    gap: 5,
  },
  avatarImage: {
    borderWidth: 1.5,
    borderColor: PURPLE,
    backgroundColor: '#EEE',
  },
  avatarFallback: {
    borderWidth: 1.5,
    borderColor: PURPLE,
    backgroundColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentUserName: {
    color: '#111',
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 82,
  },
  commentBody: {
    flex: 1,
    paddingRight: 6,
  },
  commentMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
    paddingRight: 32,
  },
  commentMeta: {
    color: '#9B9B9B',
    fontSize: 12,
  },
  commentMetaSeparator: {
    color: '#C8C8C8',
    fontSize: 12,
  },
  commentPublicationLink: {
    color: PURPLE,
    fontSize: 12,
    fontWeight: '800',
  },
  commentText: {
    color: '#A0A0A0',
    fontSize: 12,
    lineHeight: 16,
  },
  commentDeleteButton: {
    position: 'absolute',
    top: 9,
    right: 9,
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  publicationsContent: {
    padding: 8,
    paddingBottom: 96,
  },
  publicationColumns: {
    flexDirection: 'row',
    gap: 8,
  },
  publicationColumn: {
    flex: 1,
    gap: 8,
  },
  publicationCard: {
    backgroundColor: 'white',
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  publicationImage: {
    width: '100%',
    height: 160,
    backgroundColor: '#EEE',
  },
  publicationImageTall: {
    height: 210,
  },
  publicationPlaceholder: {
    width: '100%',
    height: 160,
    backgroundColor: '#F0E8EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportFab: {
    position: 'absolute',
    top: 8,
    right: 8,
    minWidth: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 8,
    zIndex: 5,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  reportCountText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '800',
  },
  publicationInfo: {
    padding: 10,
  },
  publicationDescription: {
    color: '#333',
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 6,
  },
  publicationAuthorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  publicationAuthor: {
    flex: 1,
    color: '#888',
    fontSize: 11,
    fontWeight: '500',
  },
  techniqueBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F0E8EF',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginBottom: 5,
  },
  techniqueBadgeText: {
    color: PURPLE,
    fontSize: 10,
    fontWeight: '700',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    gap: 12,
  },
  emptyText: {
    color: '#999',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: PURPLE,
    borderRadius: 10,
    paddingHorizontal: 22,
    paddingVertical: 11,
  },
  retryButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '800',
  },
  disabledItem: {
    opacity: 0.55,
  },
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 34,
  },
  deleteModalCard: {
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 18,
    padding: 26,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  deleteModalIcon: {
    width: 62,
    height: 62,
    borderRadius: 31,
    borderWidth: 2,
    borderColor: PURPLE,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  deleteModalTitle: {
    color: '#1A1A1A',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  deleteModalActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
  },
  deleteCancelButton: {
    flex: 1,
    backgroundColor: PURPLE,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  deleteCancelButtonText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '700',
  },
  deleteConfirmButton: {
    flex: 1,
    backgroundColor: 'white',
    borderWidth: 1.5,
    borderColor: PURPLE,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  deleteConfirmButtonText: {
    color: PURPLE,
    fontSize: 15,
    fontWeight: '700',
  },
  reportSafeArea: {
    flex: 1,
    backgroundColor: 'white',
  },
  reportContent: {
    flex: 1,
    paddingHorizontal: 52,
    paddingTop: 18,
  },
  reportBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginLeft: -10,
    marginBottom: 28,
  },
  reportBackText: {
    color: PURPLE,
    fontSize: 15,
    fontWeight: '800',
  },
  reportTitle: {
    color: '#262626',
    fontSize: 29,
    fontWeight: '800',
    lineHeight: 36,
    marginBottom: 30,
  },
  reportFieldGroup: {
    marginBottom: 27,
  },
  reportLabel: {
    alignSelf: 'flex-start',
    color: '#111',
    fontSize: 15,
    fontWeight: '800',
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: PURPLE,
    marginBottom: 12,
  },
  reportInput: {
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 7,
    height: 46,
    paddingHorizontal: 14,
    color: '#333',
    fontSize: 15,
  },
  reportTextArea: {
    height: 134,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  reportErrorText: {
    color: '#C0392B',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: -6,
    marginBottom: 16,
  },
  reportPrimaryButton: {
    backgroundColor: PURPLE,
    borderRadius: 7,
    minHeight: 45,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 34,
  },
  reportPrimaryButtonText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '800',
  },
  reportDangerButton: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: PURPLE,
    borderRadius: 7,
    minHeight: 45,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
  },
  reportDangerButtonText: {
    color: PURPLE,
    fontSize: 15,
    fontWeight: '800',
  },
  reportButtonDisabled: {
    opacity: 0.65,
  },
});
